### ISSUE TITLE
improved admin search behavior

### ISSUE THREAD

**Issue by gjanee** [datadryad/dryad-product-roadmap#1248]
Admin interface: when searching for a deposit by DOI, if there is an exact match, the interface should return that one exact match only.  Better yet, just redirect directly to that deposit.  Currently the UI treats DOI searches as plain text searches and returns lots of results, all but one of which are clutter.

**Comment by sfisher** [comment]
HI Greg,

You may want to try quoting the DOI such as `"10.5061/dryad.n0vr7d0"` in the search box.  I believe that will treat it as the full string rather than being tokenized at separators like slashes, dots or other things and then being relevance ranked individually.  The all terms checkbox also turns it into AND rather than only relevance ranking for terms.

**Comment by sfisher** [comment]
Also if you're trying to use this for automated processing or something where you need an exact match, you may want to use the api, like `GET https://datadryad.org/api/v2/datasets/doi%3A10.5061%2Fdryad.n0vr7d0`.

**Comment by gjanee** [comment]
Yup, thanks, quotes work.  But of course, the system could recognize what's a DOI.

**Comment by ryscher** [comment]
Agreed. It would be useful to treat DOIs as a special type of input and handle them "correctly".
