### ISSUE TITLE
Questions re: how citations are populated (DOI: 10.5061/dryad.wm37pvmpp)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2160]
If an author cites the [published data](https://datadryad.org/stash/dataset/doi:10.5061/dryad.wm37pvmpp) in their [research article](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0272360#pone.0272360.ref041) [reference 41], would that count as a citation on our dataset landing page? It's not appearing. 

Can you determine how the journal (PLOS ONE; 1932-6203) registers the references with CrossRef or Datacite? 
I’m not clear on the correct current procedure.

**Comment by ahamelers** [comment]
That would definitely count, as far as I'm aware. I don't know why it hasn't been picked up, but DataCite has [a case study article about trying to scrape references from that exact journal](https://datacite.org/blog/mysteries-in-reference-lists/)

One way to make sure it does count as a citation is to add the article DOI as a related work to the dataset. It's annoying that we would have to do this since the dream is it would happen automatically!
