### ISSUE TITLE
Clean affiliation name automatches

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#2177]
From @jleighherzog 

Sometimes, submitters enter a more detailed affiliation that just the institution name. This is a problem, because later when curators try to enter the institution name and an automatch is made, the detailed affiliation will "stick", even though the new submitter may not be from the same department as the original submitter.

We should clean the overly-detailed names from older submissions, and update the process to avoid this problem in the future.

**Comment by ryscher** [comment]
![Screenshot 2022-12-12 at 2 16 06 PM](https://user-images.githubusercontent.com/605143/207435117-a30ba166-20a0-4b30-b1ea-d10e007fad93.png)

**Comment by bryanmgee** [comment]
Something that might be worth investigating is whether this is a bug associated with the 'Import Metadata' function because the excessively long strings are often like what you would expect to have been entered in a journal's metadata fields or their manuscript. I often notice multiple linked ORCIDs and emails provided for all authors (the latter is rare in general), indicating that the submitting author used this function. Another example is given below (landing page preview was prior to any curation for this unpublished dataset).

![Screen Shot 2022-12-13 at 3 00 59 PM](https://user-images.githubusercontent.com/113212676/207653269-80e5c11c-4019-4ea3-af56-f1af596478f3.png)
![Screen Shot 2022-12-13 at 3 00 51 PM](https://user-images.githubusercontent.com/113212676/207653273-5a168d4c-f8e3-4874-ab03-46a6c6abca47.png)

**Comment by ahamelers** [comment]
I believe this was fixed via #3824 , please check
