### ISSUE TITLE
Investigate duplication in Internal Data section of Activity Log

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#2321]
**Priority**: Medium-Low
**Impact**: Save Curator time, capture accurate metadata, and improve the process of matching DOIs to published articles (pub updater workflow). 

In the **Internal Data** section of each Dryad submission, information for these fields is often duplicated or conflicting: publicationName, publicationISSN, dates. Some examples: 

> Triple ISSN: https://datadryad.org/stash/ds_admin/activity_log/104884
> 
> Double for Ecology & Evolution: https://datadryad.org/stash/ds_admin/activity_log/94238
> 
> Double ISSN for eLife: https://datadryad.org/stash/ds_admin/activity_log/104240
> 
> Very different dates for double ISSN for Molecular Ecology: https://datadryad.org/stash/ds_admin/activity_log/85473
> 
> Very different dates for double ISSN for RSOS: https://datadryad.org/stash/ds_admin/activity_log/96196
> 
> Very different dates for Proc B: https://datadryad.org/stash/ds_admin/activity_log/103191

Why does this happen? 
What can we do to capture only the most current, valid information? 

Part of the curator workflow is to perform a check of the Internal Data section, determine what information to keep, and remove any unnecessary entries. This can cost time, especially when an investigation is required to determine what information is valid to retain. _Note: For transferred submissions, there is value in preserving the initial journal information._

**Comment by ahamelers** [comment]
35405 datasets have duplicate internal data information, mainly publicationISSN (#2374). I believe we should clean these up and try to prevent them from being created in the future.

- [ ] Delete any internal data that are true duplicates
- [ ] Make a list of actual conflicting values, for further checking and fixing
- [ ] Discover where in the code internal data values are being added instead of replaced, and change this

If we wanted this to be a true has-one relationship for each type of internal data value, we could add an index on identifier_id and data_type

If we want to record changes in these values over time, they should be connected to the resource (dataset version) instead of the identifier (dataset), like all other metadata.

**Comment by ahamelers** [comment]
There are 6487 identifiers that have multiple non-duplicate publicationISSNS which don't match. It seems like they are, based on a spot check, in general ISSNs for the same journal.

83 identifiers have multiple publicationNames, and 149 have multiple manuscriptNumbers.
