### ISSUE TITLE
DOI of related journal articles not accepted by Dryad site

### ISSUE THREAD

**Issue by AmeliaCulpP1819** [datadryad/dryad-product-roadmap#3087]
Sometimes listing a dataset as a published article with journal name and (confirmed valid) DOI is not accepted by Dryad site when submitting a dataset.

Example:
<img width="1239" alt="image" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/59578414/848588cb-b3d4-4f20-9af2-da02627b4f1e">

Dryad DOI: 10.25338/B8ND28
Article DOI: 10.1002/ajp.23591

I cannot submit the dataset, and the error message links back to the Describe Dataset page, where previously entered article DOI is removed.

**Comment by bryanmgee** [comment]
This may be related to #3098; I just tried with one where the author added what is clearly the Primary Article only as an Article in the Related Works directly rather than changing the dataset to 'a published article' and adding the DOI there. I changed the designation and copied the DOI into the field and then the system gave me an error message to put a properly formatted DOI in (I put the full link, not just the unique DOI string).
