### ISSUE TITLE
Review page does not render Markdown apostrophe properly in code blocks

### ISSUE THREAD

**Issue by lauradryad** [datadryad/dryad-product-roadmap#3316]
When a user puts code blocks in their README, it looks fine in the README rich text editor, but then renders as the r&#39;. This is a common character in the code blocks, so it would be nice if it rendered the character correctly.

Example of how it looks in README editor:
![image](https://github.com/datadryad/dryad-product-roadmap/assets/124197995/d7ae596d-0879-433d-a7d7-9085ac6b2bac)

And how it renders on the landing page:
![image](https://github.com/datadryad/dryad-product-roadmap/assets/124197995/f78f250c-b75a-4125-9c1d-653aa1493ed2)

**Comment by ahamelers** [comment]
This is because of the HTML escaping we did for another ticket. So now, rather than escape everything and then unescape some specific tags, I'll do the more verbose option of escaping each of the specific tags we _don't_ want (all of them except sub and sup, for now)—this will let special characters through smoothly.

We can continue to iterate on this to make sure the subset of HTML tags allowed into the final rendering either match the editor, or make sense as a necessary or desired exception (like sub and sup)
