### ISSUE TITLE
Auto-check for Dryad DOI in Related Works

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3382]
**Priority**: Low
**Impact**: Reduce curator time in edits and reduce author error

Add this to the list of potential automated checks?

Use match case to eliminate instances of duplicated Dryad dataset DOIs as Primary Article AND in Related Works — identify duplication when these prefixes are identified in the Related Works field: **10.5061/dryad** OR **10.25349**? _(Note: "10.25349" is specific to Univ of California, Santa Barbara [USCB])_. 

In the example below, author input the article iD in the DOI field at the top of the page and also entered the same DOI as Software. 

![RW](https://github.com/datadryad/dryad-product-roadmap/assets/76497320/5d064071-639a-4027-9717-69f370e00f4d)

[Kailasha's idea!]

**Comment by ahamelers** [comment]
@jleighherzog We already have a check for duplicate DOIs in related works that does not allow them. This would have been caught automatically had both the DOIs both been input correctly. The issue here is that [one DOI is correct](https://doi.org/10.5061/dryad.2jm63xswx), and the other was incorrectly copied or assembled and just [leads to a broken link page](https://doi.org/10.5061/2jm63xswx)—they are not duplicates at all. I don't think it would be worthwhile to put in a check for dulicate _portions_ of DOIs, as that's kind of secondary to the fact that one of these DOIs isn't a DOI at all. We already have the verification checks, which stuck an asterisk (or, in the new design, a big yellow warning triangle) on the broken link
