### ISSUE TITLE
Automate reminders for AAR'd datasets

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3392]
Supplemental info: 

> Reference this ticket: [Automate reminders for AAR'd datasets](https://github.com/datadryad/dryad-product-roadmap/issues/2542#issue-1720271254)
> 
> See proposed schedule for AAR reminders here: https://docs.google.com/document/d/1pGzPalpx_TO38DHqCmv7UgK7MmvP6kZdGmoBVAr9kHk/edit#heading=h.pwdvu02p5oe6

Currently, there are ~6k datasets in 'Action required' status. The authors are not receiving reminders. Automating the reminder process will save curators time and encourage authors to return their submissions with edits in a timely manner. 

Below is the schedule and text for all 3 reminders.
_Note: for the final reminder, we're proposing that the submission is withdrawn_

**1st reminder**: 2 weeks after AAR status is set
**Monthly reminders**: 1 month after 1st reminder is sent (2-month mark)
**Final reminder** (withdraw): 1 year after AAR was set

Things to keep in mind:

Ideal to record the chase activity in the Dryad Activity Log of the data submission (Reminder 1, Reminder 2, etc., Final reminder)
If withdrawn on the Dryad Admin site, the status of the related case(s) should update in Salesforce (Note: we realize it won't close the case)
__________________________________________________________
**1st reminder**: 2 weeks after the AAR date is _first_ set
Subject line: Action required: Dryad data submission (DOI: xxxxx)

Dear {{{Case.SuppliedName}}},

Recently, we requested modifications to your Dryad dataset. As a reminder, these changes must be addressed before we can continue with our curation process and publish your dataset:

Title: "{{{Case.Dataset_Title__c}}}"
DOI: {{{Case.DOI__c}}}

Our previous email correspondence contains details on the edits required. Please let us know if you have any questions or no longer wish to proceed with the publication of the dataset. 

We hope to hear from you shortly.

The Dryad Team
[help@datadryad.org](mailto:help@datadryad.org)

**Monthly reminders**: starting 2 months after initial AAR date (1 month after 1st reminder is sent)
Subject line: Reminder: Action required for Dryad data submission (DOI: xxxxx)

Dear {{{Case.SuppliedName}}},

As a reminder, we are unable to proceed with the publication of your data submission to Dryad (DOI: xxxxx) because the changes requested in our previous correspondence have not been addressed.

If we do not receive a reply or if no action is taken within 1 year of our initial request for edits, we will withdraw your dataset.

We hope to hear from you soon.

The Dryad Team
[help@datadryad.org](mailto:help@datadryad.org)

**Final reminder**: 1 year after AAR date (2 weeks after 2nd reminder is sent) - dataset is withdrawn and notification is sent
Subject lines: Your Dryad data submission has been withdrawn (DOI: xxxxx)

Dear {{{Case.SuppliedName}}},

Because we have not received a response to our initial request and subsequent reminders regarding edits to your Dryad dataset, we have withdrawn your data submission to Dryad titled, "{{{Case.Dataset_Title__c}}}."

You are welcome to reinstate your submission. To restore your submission and resume the curation and publication processes, contact [help@datadryad.org](mailto:help@datadryad.org).  All previously provided metadata and data files will be retained as well as the assigned DOI will be reserved for one year, then, the entire dataset will be removed from our platform. 

We hope you will consider Dryad to host your future data submissions.

The Dryad Team
[help@datadryad.org](mailto:help@datadryad.org)

**Comment by jleighherzog** [comment]
@jeremywalter @mahirst @lauradryad : Please add your comments/edits/questions/clarifications to this ticket.

**Comment by mahirst** [comment]
Monthly would be good- probably easier to implement also. The text for the emails looks good.  

We have close to 6000 datasets in AR right now, so maybe 200/week, which would be completed in about 30 weeks (7.5 months). I'm assuming it won't be too overwhelming since not everyone receives our emails...

**Comment by jeremywalter** [comment]
I actually like, in theory, the 2 weeks - 1 month timing... mostly because some of those reminders hitting earlier will get a response where the author hasn't forgotten about their submission. Sometimes I come back to AARs and they were left In Progress in the first few days after I sent the AAR... this cadence would be better for those and give authors a chance to not lose context. I also have never waited a whole year for a final chase... but that should probably be a business decision. As for the automation spin-up, I advocated for 20 per day (or 100/wk) just to get started and see how it goes. It's easier to ramp up and then to back up... when I send out AARs I can get anywhere from 10-90% response rate within a week.

**Comment by mahirst** [comment]
@jeremywalter We would be sending them to people who haven't had an AR reminder in 1+ years, first, meaning they likely abandoned or forgot about the datasets. So, someone who just got an AR email last month wouldn't get another one for several months. I still vote 200/week because our queue is so low right now. We can decrease it later, but right now there's not a lot of work going around. It would be good to get more resubs back soon

**Comment by jeremywalter** [comment]
@mahirst I think you are right. Let's start with 200 and keep an eye on what comes back so we can pivot quickly if we start sinking. Certainly we can weather 100 or so extra datasets pretty easily at this point, and that is probably a generous take on what might come back while we are 'catching up'.

**Comment by jleighherzog** [comment]
Note: Laura will review all auto-notifications to ensure they're aligned with the changes we're making.

**Comment by alinvetian** [comment]
The changes were implemented as requested in this document: https://docs.google.com/document/d/1D1d422Zk5YKbax_Hp92zIciu9m0dR7JmNDMoLMa92CY/edit
