### ISSUE TITLE
New UCSB deposit, user required to pay the fee

### ISSUE THREAD

**Issue by rcurty** [datadryad/dryad-product-roadmap#3415]
The user had to agree to the fee to proceed with the submission. The depositor is an active graduate student affiliated with UCSB, and we request assistance waiving the fee.
DOI: doi:10.5061/dryad.3r2280gqv

We encountered a similar [issue](https://github.com/datadryad/dryad-product-roadmap/issues/3368) a couple of weeks ago. Could you please explain what might be causing this problem? We would also like to know how we can prevent this issue in the future.

**Comment by ryscher** [comment]
I updated payment information on the dataset and voided the invoice. 

This issue typically occurs because users do not associate their account with the university. We are working on several measures to alleviate this problem. We already made it possible for users to update their member university at any time, and we are planning to make this option visible at the end of the submission process, when payment information is displayed. We will likely also add a warning if a dataset author is affiliated with a member institution, but they haven't validated their membership. Once these changes are in place, the problem should be greatly reduced. 

See related tickets: 
- #2000 
- #2293 
- #3353
