### ISSUE TITLE
Hide affiliation list on landing page-make it click-to-reveal

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3448]
**Problem description, and links to relevant helpdesk tickets:**
We love the changes to the author and affiliation lines on the dataset landing pages! Well done, Audrey. Some additional suggestions for consideration: 

**Describe the solution you'd like:**
1. Make the author names larger than the affiliation names on the landing page, so the author names stand out more than the affiliations.
2. Make affiliation numbers smaller, to make it obvious they match the superscripts associated with the author names.
3. Hide the affiliation list, and make an affiliations button, so that clicking on the affiliations button reveals the list.

**Additional context:**
Thank you, y'all rock :-)

**Comment by jleighherzog** [comment]
Possible to add an option to show author email addresses as a click-to-reveal feature vs automatically opening a new email with the author's address included?

**Comment by ahamelers** [comment]
> Possible to add an option to show author email addresses as a click-to-reveal feature vs automatically opening a new email with the author's address included?

I think adding some kind of author info page, and the ability to hide and show the authors, can wait until we do more of a landing page redesign, along with allowing multiple affiliations

**Comment by ahamelers** [comment]
@jleighherzog in the meantime I can easily make the email addresses title text for the email links, so you don't actually need to click to see them

**Comment by jleighherzog** [comment]
1) Still in favor of an alpha listing of affiliations vs numeric (to eliminate the look of a rank). 
2) Wow! Cool feature at the end there. 
- Rather than "Add a Dryad member institution" consider "Select a member from the list" 
- Disallow the option to add a free-text entry
- I was going to suggest to add a link to the [member page](https://datadryad.org/stash/join_us#members) but maybe it's unnecessary if it's understood that only the members are included in the drop-down menu.
