### ISSUE TITLE
Remove files (DOI: 10.5061/dryad.prr4xgxv0)

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3459]
Please permanently hide/remove all data files uploaded on April 8 (there are currently 2 versions, 1 is unpublished)
DOI: **10.5061/dryad.prr4xgxv0**

The metadata will be preserved and a notice posted to inform users why no data files are available for download. 

The author explains, "Because the data providers did not agree to the use of their data in this context, which affects the dataset's ethical integrity and compliance with data usage agreements, we have already retracted our preprint published by Research Square and ResearchGate. Please refer to the attachment for more information. For this issue, could you please remove the data from Dryad to maintain ethical standards and compliance with data usage agreements? For the metadata, I would appreciate if you can keep the title and author line and remove other parts concerning the data (including abstract, methods section, README file, funding information)."

**Comment by jleighherzog** [comment]
@ryscher : Possible to prioritize this one? Maybe by end of day Wednesday?

**Comment by ryscher** [comment]
will do

**Comment by ryscher** [comment]
Files are removed from public view on Dryad and Zenodo.

@ahamelers I'm handing this ticket to you, because the alignment of the landing page is off. I didn't dig in to see whether it was due to the file hiding or something else.

**Comment by ahamelers** [comment]
It's this!

<img width="1066" alt="Screenshot 2024-07-04 at 01 02 17" src="https://github.com/datadryad/dryad-product-roadmap/assets/1749394/84006ce3-48db-4437-b98c-9b29fd7d1612">

This isn't an hr, it's a crazy long line of unbroken underscores!

This is probably because we cut out a lot of HTML tags in the editor (I don't recall if hr is still allowed). I can probably force this line to break with CSS, but it's probably better, visually, to just delete it from the abstract & replace with an `<hr/>`
