### ISSUE TITLE
Submitting edits to some datasets redirects to My datasets page instead of admin dashboard

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3590]
Evangeline identified a bug!

Usually, when we make edits to a dataset and submit those edits, the system redirects us back to the Admin dashboard. In a few cases, we have noticed that we are redirected to the My datasets page instead. I overlooked this as a normal phenomenon, but Evangeline is right that this appears to be a bug. Screenshot example attached 
![Screenshot 2024-08-20 at 8 41 57 AM](https://github.com/user-attachments/assets/a25cea12-293b-4bf1-98b2-0c4160fd2219)

**Comment by ahamelers** [comment]
This is the same as #1196. The theory in that ticket was that this can happen when a user opens multiple Dryad windows.

Potentially we could do something additional based on the role of the submitting user, instead of having it be based on the session, possibly changing this along with changing how the editors and curators are indicated in the database when we add the ability for multiple users to edit a dataset.
