### ISSUE TITLE
Auto-PPR all PALASS related journal titles

### ISSUE THREAD

**Issue by jleighherzog** [datadryad/dryad-product-roadmap#3617]
The Managing Editor of [PALASS](https://www.palass.org/) has agreed to auto-PPR all submissions associated with The Palaeontological Association:

1. Palaeontology
2. Papers in Palaeontology
3. Journal of Paleontology
4. Paleobiology

**Comment by ahamelers** [comment]
We are already automatically placing into PPR any submissions that are 1) associated with a manuscript 2) that has not already been accepted or rejected 3) and is not otherwise associated with a publication DOI

This is not done by journal, publisher, etc. but has been done universally for submissions with email-integrated manuscripts
