### ISSUE TITLE
Admin dashboard export error

### ISSUE THREAD

**Issue by sarahklippincott** [datadryad/dryad-product-roadmap#3645]
**Bug description:**
MIT user is trying to export results from the admin dashboard, using the [Export all as CSV] button. URL is https://datadryad.org/stash/admin_dashboard?page=.  She has tried in Firefox and Chrome and gets the following errors messages:

<img width="719" alt="image" src="https://github.com/user-attachments/assets/c886fa3e-c450-4a5c-a19a-ea25532a473f">

I was not able to reproduce the error (export appears to be working for me). Any thoughts on what's happening?

**Comment by ahamelers** [comment]
@sarahklippincott never mind, I found the forwarded email!

**Comment by ahamelers** [comment]
We have now had a second user report this.

There's some chatter that this might be a server issue with AWS (https://stackoverflow.com/a/34664532). I'm not sure where to look on our AWS to verify this (@ryscher?)

Since we're in contact with the second user I will also attempt to figure out if there's some issue in the specific data they're trying to download.

**Comment by ahamelers** [comment]
I was able to recreate the issue once on chrome by giving myself a tenant admin account, but now I can't get it to happen again

**Comment by ahamelers** [comment]
I was able to recreate the problem locally!
