### ISSUE TITLE
HTML 3D object file through Zenodo opens as a text file

### ISSUE THREAD

**Issue by mahirst** [datadryad/dryad-product-roadmap#3768]
An author wanted to upload an HTML 3D object, so they uploaded it through the Zenodo integration. However, when you try to download the HTML file from the reviewer-sharing page, it downloads as a text file. We found that right-clicking on the link and saving it as an HTML file works, but that’s not an intuitive workaround for something that should automatically download/open as an HTML file. Any thoughts on why this occurs and potential solutions? Here’s the [dataset reviewer page](https://datadryad.org/stash/share/fszRoczK6KDtnSagRc0lcsvUYqekb1ZNuYCIeSXk3OE#:~:text=available%20at%20Zenodo-,3d_plot.html,-README%3A%203D%20elasmobranchs), where you can see the file named “3d_plot.html”. 

DOI: 10.5061/dryad.np5hqc03w
Resource ID: 326446

**Comment by ryscher** [comment]
This file has the correct type (`text/html`) in its Dryad representation. Since it's not published yet, I am not able to see how it is represented at Zenodo. 

Options:
1. Wait until the dataset is published, at which time the Zenodo representation may work better automatically. If not, see if we can adjust it to work correctly.
2. Move the file to Dryad storage, where we can guarantee it will display properly. There would still be a "hidden" version on Zenodo that we would want to clean up after publication.

**Comment by mahirst** [comment]
Just asked the author which option she prefers- thanks!

**Comment by mahirst** [comment]
We moved the file to Dryad storage. Will update if needed. Thank you!
