### ISSUE TITLE
Updating author affiliation fails in Dryad submission

### ISSUE THREAD

**Issue by jeremywalter** [datadryad/dryad-product-roadmap#3823]
**Bug description:**
ROR listed affiliation reverts to an alternative version. Université Paris Cité is selectable but changes to University of Paris (or will not update when saving changes). Likewise if a placeholder author is added with Université Paris Cité, the system changes it to University of Paris upon Resubmit. 

**Steps to reproduce:**
Go into 10.5061/dryad.zs7h44jk0 (Resource ID 333586) -- change any current author from University of Paris to Université Paris Cité. This change will not be saved and not updated upon resubmission (for corresponding or other author(s). 

**Expected behavior:**
Updating the affiliation to Université Paris Cité should save and update the submission accordingly. The author has asked for this change specifically before publication.

**Comment by ahamelers** [comment]
In this particular case, we can change this name throughout the site so “Université Paris Cité” is what is listed for this ROR org everywhere. That would make sense since that is the actual default name for this org on ROR, and "University of Paris" should be an alternate. Possibly which name is the "default" changed recently on ROR and this hasn't been updated on our systems yet.

In general, we are not currently allowing users to select alternate/variations on ROR org names. Whatever is selected will revert to the default. Changing this so that users could enter different names for the same is technically possible, but would be a big policy change with cascading effects for development.

**Comment by ahamelers** [comment]
@jeremywalter I've fixed this one in the database and made a ticket for doing a general check and making sure the affiliations are up to date with the ror orgs (#3824)
