### ISSUE TITLE
Allow curators to create/edit journal settings in the Dryad UI

### ISSUE THREAD

**Issue by ryscher** [datadryad/dryad-product-roadmap#704]
This should probably be separate cards:
- Build a UI to add a new journal into Dryad... using only the ISSN
- Move the StashEngine::Journals.notify_contacts and StashEngine::Journals.review_contacts to be JournalRoles
- Build a UI to edit journal properties, including JournalRoles.

**Comment by ryscher** [comment]
Has some overlap with #2081, but this is still relevant.

**Comment by ahamelers** [comment]
> Build a UI to add a new journal into Dryad... using only the ISSN

Not sure how this would be possible, but with the ISSN(s) AND name, sure!

> Move the StashEngine::Journals.notify_contacts and StashEngine::Journals.review_contacts to be JournalRoles

I don't think this makes sense any longer, since these are often group email accounts, not associated with an ORCID or able to login (i.e., not Users)

> Build a UI to edit journal properties, including JournalRoles.

- JournalRoles handled in #2081 
- Will build UIs for journals and orgs as for tenants in #3275
